name = "gifuto-worker"
main = "src/index.js"
compatibility_date = "2025-11-19"

# KV を後で追加する

[[kv_namespaces]]
binding = "GIFUTO_ITEMS"
id = "b5b96a0144a248bcba744cdced43f0b7"
preview_id = "b5b96a0144a248bcba744cdced43f0b7"

[[r2_buckets]]
binding = "GIFUTO_BUCKET"
bucket_name = "gifuto-media"
